config/routes.rb
Rails.application.routes.draw do
  resources :tsubuyakis do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tsubuyaki.rb
class Tsubuyaki < ApplicationRecord
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tsubuyakis_controller.rb
class TsubuyakisController < ApplicationController
  before_action :set_tsubuyaki, only: [:timestamp, :show, :edit, :update, :destroy]
  def index
    @tsubuyaki = Tsubuyaki.new
    @tsubuyakis = Tsubuyaki.all
  end
  def show
  end
  def edit
  end
  def create
    @tsubuyaki = Tsubuyaki.new(tsubuyaki_params)
    if params[:back]
      render :new
    else
      if @tsubuyaki.save
        redirect_to tsubuyakis_path, notice: "つぶやきを作成しました！"
      else
        render :new
      end
    end
  end
  def update
    respond_to do |format|
      if @tsubuyaki.update(tsubuyaki_params)
        format.html { redirect_to @tsubuyaki, notice: 'つぶやきを更新しました！' }
      else
        format.html { render :edit }
      end
    end
  end
  def destroy
    @tsubuyaki.destroy
    respond_to do |format|
      format.html { redirect_to tsubuyakis_url, notice: 'つぶやきを削除しました！' }
    end
  end
  def confirm
    @tsubuyaki = Tsubuyaki.new(tsubuyaki_params)
    render :new if @tsubuyaki.invalid?
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tsubuyaki
      @tsubuyaki = Tsubuyaki.find(params[:id])
    end
    def tsubuyaki_params
      params.fetch(:tsubuyaki, {}).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tsubuyakis_helper.rb
module TsubuyakisHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_tsubuyakis_path
    elsif action_name == 'edit'
      tsubuyaki_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>マイつぶやき</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tsubuyakis/_form.html.erb
<%= form_with(model: @tsubuyaki, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @tsubuyaki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tsubuyaki.errors.count, "error") %> prohibited this tsubuyaki from being saved:</h2>

      <ul>
      <% @tsubuyaki.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="tsubuyaki_content">
    <%= form.label :"今どうしている？" %>
    <%= form.text_area :content, :size=>"100x5"  %>
  </div>
  <div class="actions">
    <%= form.submit  "つぶやく" %>
  </div>
<% end %>

app/views/tsubuyakis/confirm.html.erb
<div class="container">
  <header class="header clearfix">
    <p>マイつぶやき</p>
  </header>
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @tsubuyaki, url: tsubuyakis_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p>本文:<%= @tsubuyaki.content %></p>
  <%= form.submit  "つぶやく" %>
  <%= form.submit "再編集", name: 'back' %>
<% end %>
<footer class="footer clearfix">
  <p>© TSUBUYAKI Corp. All RIGHTS RESERVED.</p>
</footer>
</div>

app/views/tsubuyakis/edit.html.erb
<div class="container">
  <header class="header clearfix">
    <p>マイつぶやき</p>
  </header>

<h1>編集</h1>

<%= render 'form', tsubuyaki: @tsubuyaki %>

<%= link_to 'トップへ戻る', tsubuyakis_path %>
<footer class="footer clearfix">
  <p>© TSUBUYAKI Corp. All RIGHTS RESERVED.</p>
</footer>
</div>

app/views/tsubuyakis/index.html.erb
<div class="container">
  <header class="header clearfix">
    <p>マイつぶやきホーム</p>
  </header>
  <p id="notice"><%= notice %></p>

<%= form_with(model: @tsubuyaki, local: true ,url: confirm_tsubuyakis_path ) do |form| %>
  <div class="tsubuyaki_content">
    <%= form.label :今どうしてる？ %>
    <%= form.text_area :content, :size=>"100x5"  %>
  </div>
  <div class="actions">
    <%= form.submit value="つぶやく"%>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th colspan="3">過去のつぶやき</th>
    </tr>
  </thead>

  <tbody>
    <% @tsubuyakis.each do |tsubuyaki| %>
      <tr>
        <td id="content_width"><%= tsubuyaki.content %></td>
        <td id="edit_width"><%= link_to '編集', edit_tsubuyaki_path(tsubuyaki) %></td>
        <td id="destroy_width"><%= link_to '削除', tsubuyaki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<footer class="footer clearfix">
  <p>© TSUBUYAKI Corp. All RIGHTS RESERVED.</p>
</footer>
</div>

app/views/tsubuyakis/new.html.erb
<div class="container">
  <header class="header clearfix">
    <p>マイつぶやき</p>
  </header>

<%= render 'form', tsubuyaki: @tsubuyaki %>

<%= link_to 'トップへ戻る', tsubuyakis_path %>
<footer class="footer clearfix">
  <p>© TSUBUYAKI Corp. All RIGHTS RESERVED.</p>
</footer>
</div>

app/views/tsubuyakis/old/index_0.html.erb
<p id="notice"><%= notice %></p>

<h1>マイつぶやき</h1>

<%= form_with(model: @tsubuyaki, local: true) do |form| %>
  <div class="tsubuyaki_content">
    <%= form.label :今どうしてる？ %>
    <%= form.text_area :content %>
  </div>
  <div class="actions">
    <%= form.submit value="つぶやく"%>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th colspan="3">つぶやき一覧</th>
    </tr>
  </thead>

  <tbody>
    <% @tsubuyakis.each do |tsubuyaki| %>
      <tr>
        <td><%= tsubuyaki.content %></td>
        <td><%= link_to '編集', edit_tsubuyaki_path(tsubuyaki) %></td>
        <td><%= link_to '削除', tsubuyaki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tsubuyakis/show.html.erb
<div class="container">
  <header class="header clearfix">
    <p>マイつぶやき</p>
  </header>

<p id="notice"><%= notice %></p>

<%= link_to 'Back', tsubuyakis_path %>
</div>